<a href="https://colab.research.google.com/github/bpunar/PANDAS-EXERCISES/blob/main/DAwPy_S3_(Pandas_Series)_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [7]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int64

### **Using Dictionary**

In [9]:
d

{'a': 10, 'b': 20, 'c': 30}

In [10]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d, index=["q","c","d"])

q     NaN
c    30.0
d     NaN
dtype: float64

### Using Scalar Value

In [12]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [13]:
pd.Series(data="Ahmet", index=range(1,5))

1    Ahmet
2    Ahmet
3    Ahmet
4    Ahmet
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

In [20]:
tuple1= (1,2,3,6) #tuple

In [21]:
pd.Series(tuple1)

0    1
1    2
2    3
3    6
dtype: int64

In [22]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [23]:
pd.Series([set, list, dict])[0]

set

In [25]:
pd.Series([set, list, tuple])[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [29]:
pd.Series([set, list, tuple])[1]([2,5,7,5,8,2])

[2, 5, 7, 5, 8, 2]

In [30]:
pd.Series([set, list, tuple])[2]([2,5,7,5,8,2])

(2, 5, 7, 5, 8, 2)

In [31]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [33]:
pd.Series([sum, print, len])[0]([3, 5, 7])

15

In [34]:
pd.Series([sum, print, len])[1]([3, 5, 7])

[3, 5, 7]


In [35]:
pd.Series([sum, print, len])[2]([3, 5, 7])

3

In [51]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)]) # dict

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [37]:
mix_data = ['Aziz', 2, True]
mix_data 

['Aziz', 2, True]

In [39]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [41]:
type(ser)

pandas.core.series.Series

In [42]:
type(ser[0])

str

In [43]:
type(ser[1])

int

In [44]:
type(ser[2])

bool

In [46]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [52]:
type(arr)

numpy.ndarray

In [53]:
type(arr[0])

numpy.str_

In [54]:
type(arr[1])

numpy.str_

In [55]:
type(arr[2])

numpy.str_

### Basic Attributes of Series

In [58]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    79
1    99
2    17
3    13
4     5
5    89
6    26
dtype: int64

In [59]:
ser.dtype

dtype('int64')

In [60]:
type(ser)

pandas.core.series.Series

In [61]:
ser.shape

(7,)

In [62]:
ser.size

7

In [64]:
len(ser)

7

In [65]:
ser.ndim

1

In [66]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [67]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [68]:
for i in ser.index:
  print(i)

0
1
2
3
4
5
6


In [69]:
ser.keys

<bound method Series.keys of 0    79
1    99
2    17
3    13
4     5
5    89
6    26
dtype: int64>

In [70]:
ser.values

array([79, 99, 17, 13,  5, 89, 26])

In [71]:
ser.item

<bound method IndexOpsMixin.item of 0    79
1    99
2    17
3    13
4     5
5    89
6    26
dtype: int64>

In [72]:
ser.items()

In [73]:
list(ser.items())

[(0, 79), (1, 99), (2, 17), (3, 13), (4, 5), (5, 89), (6, 26)]

In [74]:
for index, value in ser.items():
  print(f"index: {index}, value: {value}")

index: 0, value: 79
index: 1, value: 99
index: 2, value: 17
index: 3, value: 13
index: 4, value: 5
index: 5, value: 89
index: 6, value: 26


In [76]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    24
b    14
a    11
e     4
f     6
d    10
g    15
i    15
h     1
j     4
dtype: int64

In [77]:
ser.head()

c    24
b    14
a    11
e     4
f     6
dtype: int64

In [78]:
ser.head(7)

c    24
b    14
a    11
e     4
f     6
d    10
g    15
dtype: int64

In [79]:
ser.tail()

d    10
g    15
i    15
h     1
j     4
dtype: int64

In [80]:
ser.tail(2)

h    1
j    4
dtype: int64

In [81]:
ser.sample()

a    11
dtype: int64

In [82]:
ser.sample(3)

b    14
g    15
d    10
dtype: int64

In [83]:
ser.sort_index()

a    11
b    14
c    24
d    10
e     4
f     6
g    15
h     1
i    15
j     4
dtype: int64

In [84]:
ser.sort_values()

h     1
e     4
j     4
f     6
d    10
a    11
b    14
g    15
i    15
c    24
dtype: int64

In [85]:
ser.sort_values(ascending=False)

c    24
i    15
g    15
b    14
a    11
d    10
f     6
j     4
e     4
h     1
dtype: int64

In [86]:
ser

c    24
b    14
a    11
e     4
f     6
d    10
g    15
i    15
h     1
j     4
dtype: int64

In [87]:
ser.isin([4, 6])

c    False
b    False
a    False
e     True
f     True
d    False
g    False
i    False
h    False
j     True
dtype: bool

In [88]:
ser.isin([4, 5])

c    False
b    False
a    False
e     True
f    False
d    False
g    False
i    False
h    False
j     True
dtype: bool

In [90]:
ser.isin([3, 5, 1])

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h     True
j    False
dtype: bool

In [92]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [93]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [94]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [95]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [96]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [97]:
ser2.sort_index()

Germany    2
Italy      5
Japan      4
USA        1
dtype: int64

In [98]:
ser1[1]

2

In [99]:
ser1["USA"]

1

In [100]:
ser1.Germany

2

Operations are then also done based off of index:

In [101]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [102]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [103]:
ser3[0]

'a'

In [104]:
ser3[:2]

0    a
1    b
dtype: object

In [105]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [106]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [107]:
panser[["terry","orion"]]

terry    121
orion    150
dtype: int64

In [109]:
panser["terry":"orion"]

terry      121
micheal    200
orion      150
dtype: int64

In [110]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [111]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [112]:
panser.keys

<bound method Series.keys of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [113]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [116]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [114]:
panser.values

array([121, 200, 150,  99])

In [117]:
panser.items()

In [118]:
for index, value in panser.items():
  print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [119]:
"terry" in panser

True

In [120]:
"abc" in panser

False

In [121]:
200 in panser

False

In [122]:
200 in panser.values

True

In [123]:
panser.isin([200, 500])

terry      False
micheal     True
orion      False
jason      False
dtype: bool

In [124]:
panser["terry"] = 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [125]:
panser[panser>100]

micheal    200
orion      150
dtype: int64

In [127]:
panser[panser>100] = 99
panser

terry      90
micheal    99
orion      99
jason      99
dtype: int64