<a href="https://colab.research.google.com/github/bpunar/PANDAS-EXERCISES/blob/main/DAwPy_S4_(Pandas_DataFrames%2C_Selection_and_Indexing)_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [2]:
import numpy as np
import pandas as pd

 ## Creating a DataFrame using the ``list``s of data and columns

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

In [3]:
data = [1, 3, 5, 7, 9, 18]
data

[1, 3, 5, 7, 9, 18]

In [4]:
pd.DataFrame(data=data)

0
0   1
1   3
2   5
3   7
4   9
5  18

In [5]:
pd.Series(data=data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [6]:
pd.DataFrame(data=data, columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

 ## Creating a DataFrame using a ``NumPy Arrays``

In [7]:
m = np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [8]:
df=pd.DataFrame(data=m, columns=['var1','var2','var3','var4'])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [9]:
df.head()

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [10]:
df.head(1)

var1  var2  var3  var4
0     1     3     5     7

In [11]:
df.tail(1)

var1  var2  var3  var4
2    17    19    21    23

In [12]:
df.sample(2)

var1  var2  var3  var4
0     1     3     5     7
2    17    19    21    23

In [13]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [14]:
for i in df.columns :
  print(i)

var1
var2
var3
var4


In [15]:
for i in df.columns:
  print(df[i].sum())

27
33
39
45


In [16]:
df.columns=["new1", "new2", "new3", "new4"]
df

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [17]:
df.index=["a", "b", "c"]
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [18]:
df.rename(columns={"new1":"a", "new2":"b"})

a   b  new3  new4
a   1   3     5     7
b   9  11    13    15
c  17  19    21    23

In [19]:
df.rename(index={"a":"xx", "b":2})

new1  new2  new3  new4
xx     1     3     5     7
2      9    11    13    15
c     17    19    21    23

In [20]:
df.shape

(3, 4)

In [21]:
df.shape[1]

4

In [22]:
df.ndim

2

In [23]:
df.size

12

In [24]:
len(df)

3

In [25]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
type(df.values)

numpy.ndarray

 ## Creating a DataFrame using a ``dict``

In [28]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [29]:
s1

array([5, 9, 4, 2])

In [30]:
s2

array([4, 6, 7, 8])

In [31]:
s3

array([11,  6,  9,  7])

In [32]:
my_dict ={"var1": s1, "var2":s2, "var3":s3}
my_dict

{'var1': array([5, 9, 4, 2]),
 'var2': array([4, 6, 7, 8]),
 'var3': array([11,  6,  9,  7])}

In [35]:
df1 = pd.DataFrame(my_dict)
df1

var1  var2  var3
0     5     4    11
1     9     6     6
2     4     7     9
3     2     8     7

In [36]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
[i for i in df1.index]

[0, 1, 2, 3]

In [40]:
"var2" in df1

True

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [43]:
from numpy.random import randn
randn(5,4)

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942],
       [-0.13484072,  0.39052784,  0.16690464,  0.18450186],
       [ 0.80770591,  0.07295968,  0.63878701,  0.3296463 ],
       [-0.49710402, -0.7540697 , -0.9434064 ,  0.48475165],
       [-0.11677332,  1.9017548 ,  0.23812696,  1.99665229]])

In [45]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [50]:
randn(5,4)

array([[ 1.60677986, -1.11570997, -1.38537856, -1.32966006],
       [ 0.04145994, -0.4110554 , -0.7713286 ,  0.11047741],
       [-0.80465151,  0.25354804,  0.64914775,  0.35894053],
       [-1.08047146,  0.90239776,  0.16178119,  0.83302932],
       [ 0.97571968, -0.3882387 ,  0.78331605, -0.70895374]])

In [107]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [108]:
index = 'A B C D E'.split()

In [109]:
a = 'a,b,c,d,e'.split(",")
a

['a', 'b', 'c', 'd', 'e']

In [110]:
b = 'abc,xyz,mn,2,20222'.split(",")
b

['abc', 'xyz', 'mn', '2', '20222']

In [111]:
c = 'd-8-21-lk-'.split("-")
c

['d', '8', '21', 'lk', '']

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

#### DataFrame Columns are just Series

In [112]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [113]:
type(df3["W"])

pandas.core.series.Series

In [114]:
df3[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [115]:
type(df3[["W"]])

pandas.core.frame.DataFrame

In [116]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [117]:
type(df3.W)

pandas.core.series.Series

In [ ]:
#df3["W","Z"] # This code will not work.

# Single [ ] is a method for calling series. so there can be only 1 column name in single square brackets. 
# We should use double [ ] to call multiple columns. ( like [["W, "Z"]] ).

In [118]:
df3[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [119]:
df3[["X","Y","Z"]]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965
C  0.740122  0.528813 -0.589001
D -0.758872 -0.933237  0.955057
E  1.978757  2.605967  0.683509

In [120]:
df3["a":"c"] # This type of expression is used for indexing. It is empty because there is no such index.

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [121]:
df3["A":"C"] # Returned the indexes A to C.

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [122]:
df3["A":"C"]["W"]

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [123]:
df3["A":"C"][["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813

**Creating a new column:**

In [124]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [125]:
df3['new']=df3['X']*df3['Y']
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [126]:
df3["new2"] =[1,2,3,4,5]

In [127]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [128]:
df3 = df3[["new", "new2", "W", "X", "Y", "Z"]]
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

## [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 ### Removing Columns

In [129]:
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

In [130]:
df3 = df3[["W", "X", "Y", "Z", "new", "new2"]]
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [131]:
df3.drop("new2", axis=1)

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [132]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [133]:
df3.drop(["new", "new2"], axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [138]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

 ### Removing rows

In [140]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [141]:
df3.drop("C")

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [142]:
df3.drop(index =["B"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [143]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [145]:
df4 = df3.drop("C")
df4

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selecting Rows

### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [146]:
m = np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [147]:
df4.loc[4]

var1    20
var2    36
var3    31
var4    11
Name: 4, dtype: int64

In [149]:
df4.loc[[4]]

var1  var2  var3  var4
4    20    36    31    11

In [150]:
df4.loc[2:5]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [151]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [152]:
df4.iloc[1:4]

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [154]:
df4.loc["a":"d"]

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [155]:
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [156]:
df4.iloc[3,1]

30

In [157]:
df4.loc["d","var2"]

30

In [158]:
df4.loc["d":"g","var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [159]:
df4.loc["d":"g"]

var1  var2  var3  var4
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23

In [160]:
df4.loc["d":"g"]["var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [162]:
df4.loc["d":"g","var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [161]:
df4.loc["d":"g"][["var3"]]

var3
d    25
e    31
f     9
g    38

In [163]:
df4.loc["d":"g",["var3"]]

var3
d    25
e    31
f     9
g    38

In [164]:
df4.iloc[2:5,2]

c    12
d    25
e    31
Name: var3, dtype: int64

In [165]:
df4.iloc[2:5][["var1"]]

var1
c    13
d    34
e    20

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [166]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [167]:
df3.loc["C"]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [168]:
df3.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [169]:
df3.loc[["C"]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [170]:
df3.iloc[[2]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [171]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [172]:
df3.loc["C","Z"]

-0.5890005332865824

In [173]:
df3.loc[["C"],["Z"]]

Z
C -0.589001

In [174]:
df3.loc[["A","C"],["X","Y"]]

X         Y
A  0.628133  0.907969
C  0.740122  0.528813

In [175]:
df3.iloc[[0,2],[0,3]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [177]:
df3>2

W      X      Y      Z
A   True  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False   True  False

In [178]:
df3[df3>2]

W   X         Y   Z
A  2.70685 NaN       NaN NaN
B      NaN NaN       NaN NaN
C      NaN NaN       NaN NaN
D      NaN NaN       NaN NaN
E      NaN NaN  2.605967 NaN

In [180]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [179]:
df3[df3["Z"]>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

### Conditional selection using ``.loc[]`` and ``.iloc[]``

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

### Let's learn new functions/attributes/methods on "iris dataset" 

# End of the Session