<a href="https://colab.research.google.com/github/bpunar/PANDAS-EXERCISES/blob/main/DAwPy_S4_(Pandas_DataFrames%2C_Selection_and_Indexing)_full_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import numpy as np
import pandas as pd

 ## Creating a DataFrame using the ``list``s of data and columns

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

In [2]:
data = [1, 3, 5, 7, 9, 18]
data

[1, 3, 5, 7, 9, 18]

In [3]:
pd.DataFrame(data=data)

0
0   1
1   3
2   5
3   7
4   9
5  18

In [4]:
pd.Series(data=data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [5]:
pd.DataFrame(data=data, columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

 ## Creating a DataFrame using a ``NumPy Arrays``

In [6]:
m = np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [7]:
df=pd.DataFrame(data=m, columns=['var1','var2','var3','var4'])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [8]:
df.head()

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [9]:
df.head(1)

var1  var2  var3  var4
0     1     3     5     7

In [10]:
df.tail(1)

var1  var2  var3  var4
2    17    19    21    23

In [11]:
df.sample(2)

var1  var2  var3  var4
1     9    11    13    15
2    17    19    21    23

In [12]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [13]:
for i in df.columns :
  print(i)

var1
var2
var3
var4


In [14]:
for i in df.columns:
  print(df[i].sum())

27
33
39
45


In [15]:
df.columns=["new1", "new2", "new3", "new4"]
df

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [16]:
df.index=["a", "b", "c"]
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [17]:
df.rename(columns={"new1":"a", "new2":"b"})

a   b  new3  new4
a   1   3     5     7
b   9  11    13    15
c  17  19    21    23

In [18]:
df.rename(index={"a":"xx", "b":2})

new1  new2  new3  new4
xx     1     3     5     7
2      9    11    13    15
c     17    19    21    23

In [19]:
df.shape

(3, 4)

In [20]:
df.shape[1]

4

In [21]:
df.ndim

2

In [22]:
df.size

12

In [23]:
len(df)

3

In [24]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
type(df.values)

numpy.ndarray

 ## Creating a DataFrame using a ``dict``

In [27]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [28]:
s1

array([4, 5, 4, 4])

In [29]:
s2

array([3, 8, 5, 5])

In [30]:
s3

array([10,  8, 13,  6])

In [31]:
my_dict ={"var1": s1, "var2":s2, "var3":s3}
my_dict

{'var1': array([4, 5, 4, 4]),
 'var2': array([3, 8, 5, 5]),
 'var3': array([10,  8, 13,  6])}

In [32]:
df1 = pd.DataFrame(my_dict)
df1

var1  var2  var3
0     4     3    10
1     5     8     8
2     4     5    13
3     4     5     6

In [33]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [34]:
[i for i in df1.index]

[0, 1, 2, 3]

In [35]:
"var2" in df1

True

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [36]:
from numpy.random import randn
randn(5,4)

array([[ 0.29528055,  0.01312957, -0.82924205,  1.62261463],
       [-0.35876743,  0.55479755, -0.77366763, -0.01642696],
       [-1.38217833, -1.58391626, -0.22766775, -2.14018686],
       [ 0.02050329, -0.66888887,  1.07422906, -0.26824796],
       [ 1.15193723,  0.42598583,  1.43810805,  0.31388716]])

In [37]:
randn(5,4)

array([[-0.52764738, -0.79423609, -1.31192563,  0.99957858],
       [-1.63820001,  0.10281362, -1.02320491, -0.04834339],
       [-1.50747697, -1.18181598,  1.15009885, -0.76954604],
       [-0.19962515,  1.27548507, -1.34904785,  0.87724976],
       [ 0.7068233 , -0.41462658,  0.22975734, -0.70725856]])

In [38]:
randn(5,4)

array([[ 0.84395806,  0.53432913,  0.27945599,  0.97289765],
       [-0.18871846,  1.47218226,  0.30794675,  2.69128488],
       [ 0.30576201,  0.7924308 ,  1.16713261, -0.33394597],
       [ 0.47459143, -0.08038953, -0.74683372,  0.67186153],
       [-1.40273854,  0.17187369,  0.03702894, -1.20867287]])

In [39]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
index = 'A B C D E'.split()

In [41]:
a = 'a,b,c,d,e'.split(",")
a

['a', 'b', 'c', 'd', 'e']

In [42]:
b = 'abc,xyz,mn,2,20222'.split(",")
b

['abc', 'xyz', 'mn', '2', '20222']

In [43]:
c = 'd-8-21-lk-'.split("-")
c

['d', '8', '21', 'lk', '']

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

#### DataFrame Columns are just Series

In [44]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [45]:
type(df3["W"])

pandas.core.series.Series

In [46]:
df3[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [47]:
type(df3[["W"]])

pandas.core.frame.DataFrame

In [48]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [49]:
type(df3.W)

pandas.core.series.Series

In [50]:
#df3["W","Z"] # This code will not work.

# Single [ ] is a method for calling series. so there can be only 1 column name in single square brackets. 
# We should use double [ ] to call multiple columns. ( like [["W, "Z"]] ).

In [51]:
df3[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [52]:
df3[["X","Y","Z"]]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965
C  0.740122  0.528813 -0.589001
D -0.758872 -0.933237  0.955057
E  1.978757  2.605967  0.683509

In [53]:
df3["a":"c"] # This type of expression is used for indexing. It is empty because there is no such index.

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [54]:
df3["A":"C"] # Returned the indexes A to C.

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [55]:
df3["A":"C"]["W"]

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [56]:
df3["A":"C"][["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813

**Creating a new column:**

In [57]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [58]:
df3['new']=df3['X']*df3['Y']
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [59]:
df3["new2"] =[1,2,3,4,5]

In [60]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [61]:
df3 = df3[["new", "new2", "W", "X", "Y", "Z"]]
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

## [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 ### Removing Columns

In [62]:
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

In [63]:
df3 = df3[["W", "X", "Y", "Z", "new", "new2"]]
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [64]:
df3.drop("new2", axis=1)

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [65]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [66]:
df3.drop(["new", "new2"], axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [67]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

 ### Removing rows

In [68]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [69]:
df3.drop("C")

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [70]:
df3.drop(index =["B"])

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [71]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [72]:
df4 = df3.drop("C")
df4

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

## Selecting Rows

### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [73]:
m = np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [74]:
df4.loc[4]

var1    20
var2    36
var3    31
var4    11
Name: 4, dtype: int64

In [75]:
df4.loc[[4]]

var1  var2  var3  var4
4    20    36    31    11

In [76]:
df4.loc[2:5]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [77]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [78]:
df4.iloc[1:4]

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [79]:
df4.loc["a":"d"]

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [80]:
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [81]:
df4.iloc[3,1]

30

In [82]:
df4.loc["d","var2"]

30

In [83]:
df4.loc["d":"g","var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [84]:
df4.loc["d":"g"]

var1  var2  var3  var4
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23

In [85]:
df4.loc["d":"g"]["var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [86]:
df4.loc["d":"g","var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [87]:
df4.loc["d":"g"][["var3"]]

var3
d    25
e    31
f     9
g    38

In [88]:
df4.loc["d":"g",["var3"]]

var3
d    25
e    31
f     9
g    38

In [89]:
df4.iloc[2:5,2]

c    12
d    25
e    31
Name: var3, dtype: int64

In [90]:
df4.iloc[2:5][["var1"]]

var1
c    13
d    34
e    20

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [91]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [92]:
df3.loc["C"]

W      -2.018168
X       0.740122
Y       0.528813
Z      -0.589001
new     0.391387
new2    3.000000
Name: C, dtype: float64

In [93]:
df3.iloc[2]

W      -2.018168
X       0.740122
Y       0.528813
Z      -0.589001
new     0.391387
new2    3.000000
Name: C, dtype: float64

In [94]:
df3.loc[["C"]]

W         X         Y         Z       new  new2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3

In [95]:
df3.iloc[[2]]

W         X         Y         Z       new  new2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [96]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [97]:
df3.loc["C","Z"]

-0.5890005332865824

In [98]:
df3.loc[["C"],["Z"]]

Z
C -0.589001

In [99]:
df3.loc[["A","C"],["X","Y"]]

X         Y
A  0.628133  0.907969
C  0.740122  0.528813

In [100]:
df3.iloc[[0,2],[0,3]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

In [101]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [102]:
df3.loc[['C'],['Z']]

Z
C -0.589001

In [103]:
df3.loc[['A','C','D'],['X','Z']]

X         Z
A  0.628133  0.503826
C  0.740122 -0.589001
D -0.758872  0.955057

In [104]:
df3.loc[['A','C'],['X','Z']]

X         Z
A  0.628133  0.503826
C  0.740122 -0.589001

In [105]:
df3.iloc[[0,2],[0,3]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

In [106]:
df3.iloc[0:2,0:3]

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [107]:
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [108]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [109]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df3>2

W      X      Y      Z
A   True  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False   True  False

In [111]:
df3[df3>2]

W   X         Y   Z
A  2.70685 NaN       NaN NaN
B      NaN NaN       NaN NaN
C      NaN NaN       NaN NaN
D      NaN NaN       NaN NaN
E      NaN NaN  2.605967 NaN

In [112]:
df3[df3["Z"]>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [113]:
df3[df3["Z"]>0.5]["Y"] #Series Form

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [114]:
df3[df3["Z"]>0.5][["Y"]] #Dataframe form

Y
A  0.907969
B -0.848077
D -0.933237
E  2.605967

In [115]:
df3[df3["Z"]>0.5][["Y","Z"]] # Here it shows the Y and Z columns.

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
D -0.933237  0.955057
E  2.605967  0.683509

In [116]:
df3[df3["Z"]>0.5]["Y"],["Z"] # It doesn't show the Z column here.

(A    0.907969
 B   -0.848077
 D   -0.933237
 E    2.605967
 Name: Y, dtype: float64, ['Z'])

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [117]:
df3[(df3['W']>0) & (df3['Y']<1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [118]:
df3[(df3['W']>0) & (df3['Y']<1)] = 100
df3

W           X           Y           Z
A  100.000000  100.000000  100.000000  100.000000
B  100.000000  100.000000  100.000000  100.000000
C   -2.018168    0.740122    0.528813   -0.589001
D  100.000000  100.000000  100.000000  100.000000
E    0.190794    1.978757    2.605967    0.683509

### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [119]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [120]:
df3.loc[(df3.W>0), ["X","Y"]]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [121]:
df3.loc[((df3.W>1) | (df3.Y<1)), ['Y','Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [122]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [123]:
df3.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [124]:
df3.reset_index(drop=True)

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [125]:
df3.set_index("Z")

W         X         Y
Z                                      
 0.503826  2.706850  0.628133  0.907969
 0.605965  0.651118 -0.319318 -0.848077
-0.589001 -2.018168  0.740122  0.528813
 0.955057  0.188695 -0.758872 -0.933237
 0.683509  0.190794  1.978757  2.605967

In [126]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [127]:
# Index Levels
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
inside = [1, 2, 3, 1, 2, 3, 5, 6, 7]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [128]:
hier_index=pd.MultiIndex.from_tuples(multi_index)

In [129]:
df=pd.DataFrame(np.random.randn(9,4), index = hier_index, columns=['A','B','C','D'])
df

A         B         C         D
M1 1  0.302665  1.693723 -1.706086 -1.159119
   2 -0.134841  0.390528  0.166905  0.184502
   3  0.807706  0.072960  0.638787  0.329646
M2 1 -0.497104 -0.754070 -0.943406  0.484752
   2 -0.116773  1.901755  0.238127  1.996652
   3 -0.993263  0.196800 -1.136645  0.000366
M3 5  1.025984 -0.156598 -0.031579  0.649826
   6  2.154846 -0.610259 -0.755325 -0.346419
   7  0.147027 -0.479448  0.558769  1.024810

In [130]:
df.loc["M1"]

A         B         C         D
1  0.302665  1.693723 -1.706086 -1.159119
2 -0.134841  0.390528  0.166905  0.184502
3  0.807706  0.072960  0.638787  0.329646

In [131]:
df.loc["M1"].loc[2]

A   -0.134841
B    0.390528
C    0.166905
D    0.184502
Name: 2, dtype: float64

In [132]:
df.loc["M1"].loc[[2]]

A         B         C         D
2 -0.134841  0.390528  0.166905  0.184502

In [133]:
df.index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [134]:
df.index.names

FrozenList([None, None])

In [135]:
df.index.names = ["Group", "Num"]
df

A         B         C         D
Group Num                                        
M1    1    0.302665  1.693723 -1.706086 -1.159119
      2   -0.134841  0.390528  0.166905  0.184502
      3    0.807706  0.072960  0.638787  0.329646
M2    1   -0.497104 -0.754070 -0.943406  0.484752
      2   -0.116773  1.901755  0.238127  1.996652
      3   -0.993263  0.196800 -1.136645  0.000366
M3    5    1.025984 -0.156598 -0.031579  0.649826
      6    2.154846 -0.610259 -0.755325 -0.346419
      7    0.147027 -0.479448  0.558769  1.024810

In [136]:
df.index.names

FrozenList(['Group', 'Num'])

In [137]:
df

A         B         C         D
Group Num                                        
M1    1    0.302665  1.693723 -1.706086 -1.159119
      2   -0.134841  0.390528  0.166905  0.184502
      3    0.807706  0.072960  0.638787  0.329646
M2    1   -0.497104 -0.754070 -0.943406  0.484752
      2   -0.116773  1.901755  0.238127  1.996652
      3   -0.993263  0.196800 -1.136645  0.000366
M3    5    1.025984 -0.156598 -0.031579  0.649826
      6    2.154846 -0.610259 -0.755325 -0.346419
      7    0.147027 -0.479448  0.558769  1.024810

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

In [138]:
df.xs("M1")

A         B         C         D
Num                                        
1    0.302665  1.693723 -1.706086 -1.159119
2   -0.134841  0.390528  0.166905  0.184502
3    0.807706  0.072960  0.638787  0.329646

In [139]:
df.xs(("M1",2))

A   -0.134841
B    0.390528
C    0.166905
D    0.184502
Name: (M1, 2), dtype: float64

In [140]:
df.xs(("M1",2), level=[0,1])

A         B         C         D
Group Num                                        
M1    2   -0.134841  0.390528  0.166905  0.184502

In [141]:
df.xs(key=("M3",6), level=[0,1])

A         B         C         D
Group Num                                        
M3    6    2.154846 -0.610259 -0.755325 -0.346419

In [142]:
df.xs(key=("M3",6), level=["Group","Num"])

A         B         C         D
Group Num                                        
M3    6    2.154846 -0.610259 -0.755325 -0.346419

In [143]:
# df.loc[2] # 
# df.xs(2) #

In [144]:
df.xs(2,level="Num")

A         B         C         D
Group                                        
M1    -0.134841  0.390528  0.166905  0.184502
M2    -0.116773  1.901755  0.238127  1.996652

In [145]:
df.xs(5,level="Num")

A         B         C         D
Group                                        
M3     1.025984 -0.156598 -0.031579  0.649826

In [146]:
df.xs(5,level=1)

A         B         C         D
Group                                        
M3     1.025984 -0.156598 -0.031579  0.649826

In [147]:
df["C"]

Group  Num
M1     1     -1.706086
       2      0.166905
       3      0.638787
M2     1     -0.943406
       2      0.238127
       3     -1.136645
M3     5     -0.031579
       6     -0.755325
       7      0.558769
Name: C, dtype: float64

In [148]:
df.xs("C", axis=1)

Group  Num
M1     1     -1.706086
       2      0.166905
       3      0.638787
M2     1     -0.943406
       2      0.238127
       3     -1.136645
M3     5     -0.031579
       6     -0.755325
       7      0.558769
Name: C, dtype: float64

In [149]:
df

A         B         C         D
Group Num                                        
M1    1    0.302665  1.693723 -1.706086 -1.159119
      2   -0.134841  0.390528  0.166905  0.184502
      3    0.807706  0.072960  0.638787  0.329646
M2    1   -0.497104 -0.754070 -0.943406  0.484752
      2   -0.116773  1.901755  0.238127  1.996652
      3   -0.993263  0.196800 -1.136645  0.000366
M3    5    1.025984 -0.156598 -0.031579  0.649826
      6    2.154846 -0.610259 -0.755325 -0.346419
      7    0.147027 -0.479448  0.558769  1.024810

### Let's learn new functions/attributes/methods on "iris dataset" 

In [150]:
import seaborn as sns

In [151]:
df = sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [152]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [153]:
df.shape

(150, 5)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [155]:
df.sample(4)

sepal_length  sepal_width  petal_length  petal_width     species
58            6.6          2.9           4.6          1.3  versicolor
83            6.0          2.7           5.1          1.6  versicolor
69            5.6          2.5           3.9          1.1  versicolor
124           6.7          3.3           5.7          2.1   virginica

In [156]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [157]:
df.describe().transpose()

count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [158]:
df.describe(include="all") # "number" and "object" can be used as include/exclude parameter

sepal_length  sepal_width  petal_length  petal_width    species
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.057333      3.758000     1.199333        NaN
std         0.828066     0.435866      1.765298     0.762238        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN

In [159]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [160]:
df.corr()[["sepal_length"]]

sepal_length
sepal_length      1.000000
sepal_width      -0.117570
petal_length      0.871754
petal_width       0.817941

In [161]:
df["petal_length"].corr(df["petal_width"])

0.9628654314027961

In [162]:
df["species"].value_counts()

virginica     50
setosa        50
versicolor    50
Name: species, dtype: int64

In [163]:
df["species"].value_counts(dropna=False)

virginica     50
setosa        50
versicolor    50
Name: species, dtype: int64

In [164]:
df["species"].value_counts(dropna=False, normalize=True)

virginica     0.333333
setosa        0.333333
versicolor    0.333333
Name: species, dtype: float64

In [165]:
df.species.nunique()

3

In [166]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [167]:
df.loc[df["species"] == "setosa", "sepal_length"]

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
30    4.8
31    5.4
32    5.2
33    5.5
34    4.9
35    5.0
36    5.5
37    4.9
38    4.4
39    5.1
40    5.0
41    4.5
42    4.4
43    5.0
44    5.1
45    4.8
46    5.1
47    4.6
48    5.3
49    5.0
Name: sepal_length, dtype: float64

In [168]:
df[(df.sepal_length>4) & (df.sepal_length<5)]

sepal_length  sepal_width  petal_length  petal_width     species
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
11            4.8          3.4           1.6          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
13            4.3          3.0           1.1          0.1      setosa
22            4.6          3.6           1.0          0.2      setosa
24            4.8          3.4           1.9          0.2      setosa
29            4.7          3.2           1.6          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
34            4.9          3.1           1.5          0.2      setosa
37            4.9          3.6           1.4          0.1      setosa
38            4.4          3.0           1.3          0.2      setosa
41            4.5          2.3           1.3          0.3      setosa
42            4.4          3.2           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
47            4.6          3.2           1.4          0.2      setosa
57            4.9          2.4           3.3          1.0  versicolor
106           4.9          2.5           4.5          1.7   virginica

In [169]:
df.loc[df["species"]=="setosa", "sepal_length"]

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
30    4.8
31    5.4
32    5.2
33    5.5
34    4.9
35    5.0
36    5.5
37    4.9
38    4.4
39    5.1
40    5.0
41    4.5
42    4.4
43    5.0
44    5.1
45    4.8
46    5.1
47    4.6
48    5.3
49    5.0
Name: sepal_length, dtype: float64

In [170]:
df[(df.species == "virginica") & (df.sepal_length>4)  & (df.sepal_length<5)]

sepal_length  sepal_width  petal_length  petal_width    species
106           4.9          2.5           4.5          1.7  virginica

In [171]:
df.sort_values(by = 'sepal_length', ascending = True)

sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

# End of the Session